//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olimpiad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Olimpiads
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Olimpiads()
        {
            this.SportGames = new HashSet<SportGames>();
        }
    
        public int Id { get; set; }
        public string OlimpiadName { get; set; }
        public int IdOlimpiadType { get; set; }
        public int IdCountry { get; set; }
        public int IdCity { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual Countries Countries { get; set; }
        public virtual OlimpiadTypes OlimpiadTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SportGames> SportGames { get; set; }
    }
}
