//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olimpiad
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OlympiadsEntities : DbContext
    {
        public OlympiadsEntities()
            : base("name=OlympiadsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Athlets> Athlets { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Olimpiads> Olimpiads { get; set; }
        public virtual DbSet<OlimpiadTypes> OlimpiadTypes { get; set; }
        public virtual DbSet<Results> Results { get; set; }
        public virtual DbSet<SportGames> SportGames { get; set; }
        public virtual DbSet<SportTypes> SportTypes { get; set; }
    }
}
