//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework_4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        public int Id { get; set; }
        public int IdFirstClub { get; set; }
        public int IdSecondClub { get; set; }
        public int FirstClubGoals { get; set; }
        public int SecondClubGoals { get; set; }
        public string PlayersWhoGoals { get; set; }
        public System.DateTime GameDate { get; set; }
    
        public virtual Clubs Clubs { get; set; }
        public virtual Clubs Clubs1 { get; set; }
    }
}
